const priceSets={"Diseñador":{5:450,10:850,30:2300},"Árabe":{5:300,10:550,30:1500},"Nicho":{5:850,10:1500,30:4100},"Mykonos":{5:380,10:720,30:2000}};
const products=[
['Versace Eros Flame','Diseñador','Hombre'],['Invictus Parfum','Diseñador','Hombre'],['Invictus Victory EDP','Diseñador','Hombre'],['Stronger With You Intensely','Diseñador','Hombre'],['Bad Boy Cobalt','Diseñador','Hombre'],['Acqua di Giò Profumo','Diseñador','Hombre'],['Le Beau Paradise Garden','Diseñador','Hombre'],['MYSLF L’Absolu','Diseñador','Hombre'],['Dolce & Gabbana The One EDP','Diseñador','Hombre'],['Bleu de Chanel EDP','Diseñador','Hombre'],['Polo 67','Diseñador','Hombre'],['One Million Royal','Diseñador','Hombre'],['Valentino Uomo Coral Fantasy','Diseñador','Hombre'],['Fahrenheit','Diseñador','Hombre'],['Invictus EDT','Diseñador','Hombre'],['Acqua di Giò EDT','Diseñador','Hombre'],['Acqua di Giò Elixir','Diseñador','Hombre'],
['Black Opium','Diseñador','Mujer'],['Acqua di Gioia','Diseñador','Mujer'],['La Vie Est Belle Soleil Cristal','Diseñador','Mujer'],['212 EDT Carolina Herrera','Diseñador','Mujer'],['Good Girl','Diseñador','Mujer'],['Idôle Aura','Diseñador','Mujer'],['L’Imperatrice','Diseñador','Mujer'],['Versace Versense','Diseñador','Mujer'],['Valentino Donna Green Stravaganza','Diseñador','Mujer'],['212 VIP Rosé Elixir','Diseñador','Mujer'],['Sì Intense','Diseñador','Mujer'],['Trésor Midnight Rose','Diseñador','Mujer'],['Olympea Solar','Diseñador','Mujer'],['Narciso Rodríguez Pure Musc','Diseñador','Mujer'],['My Way Intense','Diseñador','Mujer'],
['Rayhaan Elixir','Árabe','Hombre'],['Odyssey Homme','Árabe','Hombre'],['Glacier Bold','Árabe','Hombre'],['Safari Breeze','Árabe','Hombre'],['9 PM Afnan','Árabe','Hombre'],['Dubai Night Midnight','Árabe','Hombre'],['Hawas Malibú','Árabe','Hombre'],['Atlas Lattafa','Árabe','Hombre'],['Hawas Fire','Árabe','Hombre'],['Club de Nuit Milestone','Árabe','Hombre'],['Rayhaan Azul','Árabe','Hombre'],['Hawas Verde','Árabe','Hombre'],
['Haya Lattafa','Árabe','Mujer'],['Delilah Blanc','Árabe','Mujer'],['Badee Al Oud Blush','Árabe','Mujer'],['Quimmah Woman','Árabe','Mujer'],['Eclaire Lattafa','Árabe','Mujer'],['Victoria Lattafa','Árabe','Mujer'],['Eclaire Pistache','Árabe','Mujer'],['Yara Elixir','Árabe','Mujer'],['Yara Rosa','Árabe','Mujer'],['Yum Yum Armaf','Árabe','Mujer'],
['Odyssey Mandarin Sky','Árabe','Unisex'],['Lovely Chérie','Árabe','Unisex'],['Al Haramain Conception','Árabe','Unisex'],['Honor & Glory','Árabe','Unisex'],['Khamrah','Árabe','Unisex'],['Liquid Brun','Árabe','Unisex'],['Nebras','Árabe','Unisex'],['Musamam White Intense','Árabe','Unisex'],
['Erba Pura Xerjoff','Nicho','Unisex'],['Tobacco Vanille Tom Ford','Nicho','Unisex'],['Arabians Tonka Montale','Nicho','Unisex'],['Glich','Mykonos','Unisex'],['Conquer','Mykonos','Unisex']
].map((p,i)=>({id:i+1,name:p[0],type:p[1],gender:p[2],prices:priceSets[p[1]]}));
let cart=[],filter='all',selected=null,selectedSize=5;
const $=s=>document.querySelector(s), money=n=>'$'+n.toLocaleString('es-UY');
function render(){const q=$('#search').value.toLowerCase();const list=products.filter(p=>(filter==='all'||p.type===filter||p.gender===filter)&&p.name.toLowerCase().includes(q));$('#productCount').textContent=`${products.length} fragancias cargadas · completando catálogo e imágenes`;$('#productGrid').innerHTML=list.map(p=>`<article class="card"><div class="product-art"><div></div></div><small>${p.type} · ${p.gender}</small><h3>${p.name}</h3><div class="price">desde ${money(p.prices[5])}</div><button onclick="openProduct(${p.id})">Elegir medida</button></article>`).join('')}
window.openProduct=id=>{selected=products.find(p=>p.id===id);selectedSize=5;$('#modalMeta').textContent=`${selected.type} · ${selected.gender}`;$('#modalName').textContent=selected.name;$('#sizes').innerHTML=Object.entries(selected.prices).map(([s,v])=>`<button class="${+s===5?'active':''}" onclick="pickSize(${s},this)">${s} ml<br>${money(v)}</button>`).join('');$('#modal').classList.add('open')};
window.pickSize=(s,b)=>{selectedSize=+s;document.querySelectorAll('#sizes button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};
function add(){if(!selected)return;cart.push({...selected,size:selectedSize,price:selected.prices[selectedSize]});$('#modal').classList.remove('open');renderCart()}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><b>${x.name}</b><br><small>${x.size} ml · ${money(x.price)}</small> <button onclick="removeItem(${i})">×</button></div>`).join(''):'<p>Tu carrito está vacío.</p>';$('#total').textContent=money(cart.reduce((a,x)=>a+x.price,0))}
window.removeItem=i=>{cart.splice(i,1);renderCart()};function drawer(on){$('#drawer').classList.toggle('open',on);$('#backdrop').classList.toggle('open',on)}
$('#openCart').onclick=()=>drawer(true);$('#closeCart').onclick=()=>drawer(false);$('#backdrop').onclick=()=>drawer(false);$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#addToCart').onclick=add;$('#search').oninput=render;
$('#filters').onclick=e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;document.querySelectorAll('#filters button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');render()};
$('#checkout').onclick=()=>{if(!cart.length)return alert('Agregá al menos un perfume al carrito.');const lines=cart.map(x=>`• ${x.name} — ${x.size} ml — ${money(x.price)}`);const total=cart.reduce((a,x)=>a+x.price,0);const text=`Hola Colonia Decants 👋\nQuiero hacer este pedido:\n\n${lines.join('\n')}\n\nTotal: ${money(total)}`;window.open('https://wa.me/59898993292?text='+encodeURIComponent(text),'_blank')};render();renderCart();