const priceSets={"Diseñador":{5:450,10:850,30:2300},"Árabe":{5:300,10:550,30:1500},"Nicho":{5:850,10:1500,30:4100},"Mykonos":{5:380,10:720,30:2000}};
const rows=[
['Versace Eros Flame','Diseñador','Hombre'],['Invictus Parfum','Diseñador','Hombre'],['Invictus Victory EDP','Diseñador','Hombre'],['Stronger With You Intensely','Diseñador','Hombre'],['Bad Boy Cobalt','Diseñador','Hombre'],['Acqua di Giò Profondo','Diseñador','Hombre'],['Le Beau Narcisse JPG','Diseñador','Hombre'],['MYSLF L’Absolu','Diseñador','Hombre'],['Dolce & Gabbana The One EDP','Diseñador','Hombre'],['Bleu de Chanel EDP','Diseñador','Hombre'],['Polo 67','Diseñador','Hombre'],['One Million Royal','Diseñador','Hombre'],['Valentino Uomo Coral Fantasy','Diseñador','Hombre'],['Fahrenheit','Diseñador','Hombre'],['Invictus EDT','Diseñador','Hombre'],['Acqua di Giò EDT','Diseñador','Hombre'],['Acqua di Giò Elixir','Diseñador','Hombre'],['Ralph’s Club Parfum','Diseñador','Hombre'],['BOSS Bottled','Diseñador','Hombre'],['Y Le Parfum','Diseñador','Hombre'],['Bvlgari Man Wood Essence','Diseñador','Hombre'],['Armani Code Parfum','Diseñador','Hombre'],['Nautica Voyage','Diseñador','Hombre'],['212 VIP Black Elixir Cab','Diseñador','Hombre'],['Le Male Le Parfum','Diseñador','Hombre'],
['Black Opium','Diseñador','Mujer'],['Acqua di Gioia','Diseñador','Mujer'],['La Vie Est Belle Soleil Cristal','Diseñador','Mujer'],['212 EDT Carolina Herrera','Diseñador','Mujer'],['Good Girl','Diseñador','Mujer'],['Idôle Aura','Diseñador','Mujer'],['L’Imperatrice','Diseñador','Mujer'],['Versace Versense','Diseñador','Mujer'],['Valentino Donna Green Stravaganza','Diseñador','Mujer'],['212 VIP Rosé Elixir','Diseñador','Mujer'],['Sì Intense','Diseñador','Mujer'],['Trésor Midnight Rose','Diseñador','Mujer'],['Olympea Solar','Diseñador','Mujer'],['Narciso Rodríguez Pure Musc Blanc','Diseñador','Mujer'],['My Way Parfum','Diseñador','Mujer'],['Good Girl Blush Elixir','Diseñador','Mujer'],['Miracle Lancôme','Diseñador','Mujer'],
['Rayhaan Elixir','Árabe','Hombre'],['Odyssey Homme','Árabe','Hombre'],['Glacier Bold','Árabe','Hombre'],['Safari Breeze','Árabe','Hombre'],['9 PM Afnan','Árabe','Hombre'],['Dubai Night Midnight','Árabe','Hombre'],['Hawas Malibú','Árabe','Hombre'],['Atlas Lattafa','Árabe','Hombre'],['Hawas Fire','Árabe','Hombre'],['Club de Nuit Milestone','Árabe','Hombre'],['Rayhaan Azul','Árabe','Hombre'],['Hawas Verde','Árabe','Hombre'],['Club de Nuit Intense Man','Árabe','Hombre'],['Hawas Ice','Árabe','Hombre'],['Asad Elixir Lattafa','Árabe','Hombre'],['Odyssey Mega','Árabe','Hombre'],['Mandarinsky Elixir','Árabe','Hombre'],['Momento de Riffs','Árabe','Hombre'],['Khamrah Qahwa','Árabe','Hombre'],['Rayhan Pacific Aloha','Árabe','Hombre'],
['Haya Lattafa','Árabe','Mujer'],['Delilah Blanc','Árabe','Mujer'],['Badee Al Oud Blush','Árabe','Mujer'],['Quimmah Woman','Árabe','Mujer'],['Eclaire Lattafa','Árabe','Mujer'],['Victoria Lattafa','Árabe','Mujer'],['Eclaire Pistache','Árabe','Mujer'],['Yara Elixir','Árabe','Mujer'],['Yara Rosa','Árabe','Mujer'],['Yum Yum Armaf','Árabe','Mujer'],['Hawas Diva','Árabe','Mujer'],['Angham Second Song','Árabe','Mujer'],['Odyssey Candee','Árabe','Mujer'],
['Odyssey Mandarin Sky','Árabe','Unisex'],['Lovely Chérie','Árabe','Unisex'],['Al Haramain Conception','Árabe','Unisex'],['Honor & Glory','Árabe','Unisex'],['Khamrah','Árabe','Unisex'],['Liquid Brun','Árabe','Unisex'],['Nebras','Árabe','Unisex'],['Musamam White Intense','Árabe','Unisex'],['Amber Oud Gold Edition','Árabe','Unisex'],['Vulcan Feu','Árabe','Unisex'],['Club de Nuit Untold','Árabe','Unisex'],
['Erba Pura Xerjoff','Nicho','Unisex'],['Tobacco Vanille Tom Ford','Nicho','Unisex'],['Arabians Tonka Montale','Nicho','Unisex'],['Glich','Mykonos','Unisex'],['Conquer','Mykonos','Unisex'],
["Acqua di Giò Profumo","Diseñador","Hombre"],
["Le Beau Paradise Garden","Diseñador","Hombre"],
["Y EDP Yves Saint Laurent","Diseñador","Hombre"],
["212 Sexy Man","Diseñador","Hombre"],
["Tag Her","Árabe","Mujer"],
["Fakhar Rose","Árabe","Mujer"],
["Guess Bella Vita","Diseñador","Mujer"],
["24 Faubourg","Diseñador","Mujer"],
["Coach Dreams Sunset","Diseñador","Mujer"],
["Mon Paris","Diseñador","Mujer"],
["CK Be","Diseñador","Unisex"],
["Gucci Guilty Essence","Diseñador","Hombre"],
["Azzaro The Most Wanted EDT Intense","Diseñador","Hombre"],
["Versace Eros EDT","Diseñador","Hombre"],
["La Vie Est Belle Elixir","Diseñador","Mujer"],
["Kenzo Flower","Diseñador","Mujer"],
["DKNY Be Delicious EDP","Diseñador","Mujer"],
["Asad Bourbon","Árabe","Hombre"]
];
const images={
  "Versace Eros Flame": "8.jpg",
  "Acqua di Giò Profondo": "11.webp",
  "Le Beau Narcisse JPG": "9.webp",
  "Polo 67": "7.jpg",
  "Bleu de Chanel EDP": "6.jpg",
  "Valentino Uomo Coral Fantasy": "5.webp",
  "Ralph’s Club Parfum": "4.jpg",
  "BOSS Bottled": "3.webp",
  "Acqua di Giò EDT": "2.webp",
  "Acqua di Giò Elixir": "1.webp",
  "Bvlgari Man Wood Essence": "WhatsApp Image 2026-09-10 at 7.47.46 PM.jpeg",
  "One Million Royal": "WhatsApp Image 2026-09-10 at 7.47.46 PM (1).jpeg",
  "Stronger With You Intensely": "WhatsApp Image 2026-09-10 at 7.47.47 PM (1).jpeg",
  "Invictus Parfum": "WhatsApp Image 2026-09-10 at 7.47.47 PM (2).jpeg",
  "MYSLF L’Absolu": "WhatsApp Image 2026-09-10 at 7.47.48 PM.jpeg",
  "Dolce & Gabbana The One EDP": "WhatsApp Image 2026-09-10 at 7.47.48 PM (1).jpeg",
  "Invictus EDT": "WhatsApp Image 2026-09-10 at 7.47.48 PM (3).jpeg",
  "Acqua di Giò Profumo": "WhatsApp Image 2026-09-10 at 7.47.47 PM.jpeg",
  "Le Beau Paradise Garden": "WhatsApp Image 2026-09-10 at 7.47.47 PM (3).jpeg",
  "Y EDP Yves Saint Laurent": "WhatsApp Image 2026-09-10 at 7.47.48 PM (2).jpeg",
  "Bad Boy Cobalt": "images/bad-boy-cobalt.webp",
  "212 Sexy Man": "images/212-sexy-man.webp",
  "Invictus Victory EDP": "images/invictus-victory.webp",
  "Tag Her": "images/tag-her.jpg",
  "Fakhar Rose": "images/fakhar-rose.webp",
  "Odyssey Candee": "images/odyssey-candee.jpg",
  "Narciso Rodríguez Pure Musc Blanc": "images/narciso-rodriguez-pure-musc.jpg",
  "Guess Bella Vita": "images/guess-bella-vita.jpg",
  "24 Faubourg": "images/24-faubourg.webp",
  "Miracle Lancôme": "images/miracle.jpg",
  "Coach Dreams Sunset": "images/coach-dreams-sunset.jpg",
  "Mon Paris": "images/mon-paris.webp",
  "CK Be": "images/ck-be.webp",
  "Gucci Guilty Essence": "images/gucci-guilty-essence.jpg",
  "Nautica Voyage": "images/nautica-voyage.jpg",
  "Azzaro The Most Wanted EDT Intense": "images/azzaro-the-most-wanted-edt-intense.jpg",
  "Le Male Le Parfum": "images/le-male-le-parfum.jpg",
  "212 VIP Black Elixir Cab": "images/212-vip-black-elixir-cab.jpg",
  "My Way Parfum": "images/my-way-parfum.jpg",
  "Versace Eros EDT": "images/versace-eros-edt.webp",
  "La Vie Est Belle Elixir": "images/la-vie-est-belle-elixir.jpg",
  "Olympea Solar": "images/olympea-solar.jpg",
  "Kenzo Flower": "images/kenzo-flower.jpg",
  "DKNY Be Delicious EDP": "images/dkny-be-delicious-edp.webp",
  "Good Girl Blush Elixir": "images/good-girl-blush-elixir.jpg",
  "Asad Bourbon": "images/asad-bourbon.webp",
  "Amber Oud Gold Edition": "images/amber-oud-gold-edition.jpg",
  "Momento de Riffs": "images/momento-de-riffs.jpg",
  "Asad Elixir Lattafa": "images/asad-elixir.webp",
  "Odyssey Mega": "images/odyssey-mega.jpg",
  "Club de Nuit Intense Man": "images/club-de-nuit-intense-man.jpg",
  "Khamrah Qahwa": "images/khamrah-qahwa.jpg",
  "Rayhan Pacific Aloha": "images/rayhaan-aloha.webp",
  "Club de Nuit Untold": "images/club-de-nuit-untold.jpg",
  "Mandarinsky Elixir": "images/mandarinsky-elixir.jpg",
  "Nebras": "images/nebras.jpg",
  "Vulcan Feu": "images/vulcan-feu.webp",
  "Idôle Aura": "images/idole-aura.jpg",
  "Haya Lattafa": "images/haya.jpg",
  "Delilah Blanc": "images/delilah-blanc.jpg",
  "Badee Al Oud Blush": "images/badee-al-oud-blush.webp",
  "Quimmah Woman": "images/quimmah-woman.webp",
  "Eclaire Lattafa": "images/eclaire.jpg",
  "Black Opium": "images/black-opium.jpg",
  "Acqua di Gioia": "images/acqua-di-gioia.webp",
  "La Vie Est Belle Soleil Cristal": "images/la-vie-est-belle-soleil-cristal.webp",
  "212 EDT Carolina Herrera": "images/212-edt.jpg",
  "Good Girl": "images/good-girl.jpg",
  "Rayhaan Elixir": "images/rayhaan-elixir.webp",
  "Odyssey Homme": "images/odyssey-homme.webp",
  "Glacier Bold": "images/glacier-bold.webp",
  "Safari Breeze": "images/safari-breeze.jpg",
  "9 PM Afnan": "images/9-pm.jpg",
  "Dubai Night Midnight": "images/dubai-night-midnight.webp",
  "Victoria Lattafa": "images/victoria.webp",
  "Eclaire Pistache": "images/eclaire-pistache.webp",
  "Yara Elixir": "images/yara-elixir.jpg",
  "Yara Rosa": "images/yara-rosa.jpg",
  "Yum Yum Armaf": "images/yum-yum.jpg",
  "Tobacco Vanille Tom Ford": "images/tobacco-vanille.jpg",
  "Arabians Tonka Montale": "images/arabians-tonka.webp",
  "Hawas Malibú": "images/hawas-malibu.jpg",
  "Atlas Lattafa": "images/atlas-lattafa.jpg",
  "Hawas Fire": "images/hawas-fire.jpg",
  "Club de Nuit Milestone": "images/club-de-nuit-milestone.jpeg",
  "Rayhaan Azul": "images/rayhaan-azul.webp",
  "Hawas Verde": "images/hawas-verde.jpg",
  "Glich": "images/glich.webp",
  "Conquer": "images/conquer.webp",
  "L’Imperatrice": "images/limperatrice.jpg",
  "Versace Versense": "images/versace-versense.jpeg",
  "Valentino Donna Green Stravaganza": "images/valentino-donna-green-stravaganza.jpg",
  "212 VIP Rosé Elixir": "images/212-vip-rose-elixir.png",
  "Sì Intense": "images/si-intense.jpg",
  "Trésor Midnight Rose": "images/tresor-midnight-rose.png",
  "Odyssey Mandarin Sky": "images/odyssey-mandarin-sky.png",
  "Lovely Chérie": "images/lovely-cherie.jpg",
  "Al Haramain Conception": "images/al-haramain-conception.jpg",
  "Honor & Glory": "images/honor-and-glory.png",
  "Khamrah": "images/khamrah.jpg",
  "Liquid Brun": "images/liquid-brun.jpg",
  "Erba Pura Xerjoff": "images/erba-pura.jpg"
};
const products=rows.map((p,i)=>({id:i+1,name:p[0],type:p[1],gender:p[2],prices:priceSets[p[1]],image:images[p[0]]||null}));
let cart=[],filter='all',selected=null,selectedSize=5;
const $=s=>document.querySelector(s), money=n=>'$'+n.toLocaleString('es-UY');
function art(p){return p.image?`<img src="${p.image}" alt="${p.name}" onerror="this.remove();this.parentElement.innerHTML='<div></div>'">`:'<div></div>'}
function render(){const q=$('#search').value.toLowerCase().trim();const list=products.filter(p=>(filter==='all'||p.type===filter||p.gender===filter)&&p.name.toLowerCase().includes(q));$('#productCount').textContent=`${products.length} fragancias cargadas`;$('#productGrid').innerHTML=list.map(p=>`<article class="card"><div class="product-art">${art(p)}</div><small>${p.type} · ${p.gender}</small><h3>${p.name}</h3><div class="price">desde ${money(p.prices[5])}</div><button onclick="openProduct(${p.id})">Elegir medida</button></article>`).join('')}
window.openProduct=id=>{selected=products.find(p=>p.id===id);selectedSize=5;$('#modalMeta').textContent=`${selected.type} · ${selected.gender}`;$('#modalName').textContent=selected.name;$('#sizes').innerHTML=Object.entries(selected.prices).map(([s,v])=>`<button class="${+s===5?'active':''}" onclick="pickSize(${s},this)">${s} ml<br>${money(v)}</button>`).join('');$('#modal').classList.add('open')};
window.pickSize=(s,b)=>{selectedSize=+s;document.querySelectorAll('#sizes button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};
function add(){if(!selected)return;cart.push({...selected,size:selectedSize,price:selected.prices[selectedSize]});$('#modal').classList.remove('open');renderCart()}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><b>${x.name}</b><br><small>${x.size} ml · ${money(x.price)}</small> <button onclick="removeItem(${i})">×</button></div>`).join(''):'<p>Tu carrito está vacío.</p>';$('#total').textContent=money(cart.reduce((a,x)=>a+x.price,0))}
window.removeItem=i=>{cart.splice(i,1);renderCart()};function drawer(on){$('#drawer').classList.toggle('open',on);$('#backdrop').classList.toggle('open',on)}
$('#openCart').onclick=()=>drawer(true);$('#closeCart').onclick=()=>drawer(false);$('#backdrop').onclick=()=>drawer(false);$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#addToCart').onclick=add;$('#search').oninput=render;
$('#filters').onclick=e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;document.querySelectorAll('#filters button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');render()};
$('#checkout').onclick=()=>{if(!cart.length)return alert('Agregá al menos un perfume al carrito.');const lines=cart.map(x=>`• ${x.name} — ${x.size} ml — ${money(x.price)}`);const total=cart.reduce((a,x)=>a+x.price,0);const text=`Hola Colonia Decants 👋\nQuiero hacer este pedido:\n\n${lines.join('\n')}\n\nTotal: ${money(total)}`;window.open('https://wa.me/59898993292?text='+encodeURIComponent(text),'_blank')};render();renderCart();
